### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by m273d15** [swp-fu-eid/eid-fu-swp#7]
Setup CI for project

**Comment by m273d15** [comment]
I moved this repo to the new organisation `swp-fu-eid` and activated the travis ci via my private account for this repo. Now it should be enabled for any user. @Armagetron  please verify this.
Todo: We have to create a yaml configuration. Which requirements are the foundation to create the configuration?

**Comment by BenjaminKeller** [comment]
I think we need npm along with yasmine, frisby and jquery for eid client testing. Is that your question?

**Comment by Armagetron** [comment]
Travis should work now. I will setup a CI pipeline tomorrow.

**Comment by BenjaminKeller** [comment]
You can add my js-tests in branch check_for_eidclient. They are located in `static/test/`.

**Comment by Armagetron** [comment]
First steps in 8dbae111ec6dc5f33a68fbec74cab889e08c557f

**Comment by Armagetron** [comment]
The pipeline is running so far. However the communication between the different containers causes some trouble.

Maybe someone with more nodejs experience can look into this.

**Comment by Armagetron** [comment]
Current error is: ```Failed: request to https://eid.local/ failed, reason: getaddrinfo ENOTFOUND eid.local eid.local:443```

Somehow the URL is not resolved.

**Comment by BenjaminKeller** [comment]
Try to add the following lines to the docker compose file:
```
    extra_hosts:
    - "eid.com:192.168.99.100"
```
I use this as my docker-compose.test.yml file, for example:
```
version: '2.1'

# mostly extending from main .yml
services:
  test-e2e:
    build: test/e2e
    restart: "no"
    environment:
    - BOILERPLATE_DOMAIN
    #- BOILERPLATE_IPV4_16PREFIX
    #- BOILERPLATE_IPV6_ADDRESS
    depends_on:
    - www
    networks:
    - front
    extra_hosts:
    - "eid.com:192.168.99.100"
```
